server:
  port: 8090
app:
  key: ${GEMINI_KEY}
  aimodel: gemini-3-flash-preview
  url: https://generativelanguage.googleapis.com/v1beta/

spring:
  ai:
    openai:
      api-key: ${app.key}
      base-url: ${app.url}
      chat:
        model: ${app.aimodel}
